/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#b1c6f7",
        "primary-container": "#4d8efe",
        "error": "#ffb4ab",
        "tertiary-container": "#db760f",
        "on-primary": "#002e69",
        "surface-container-high": "#2a2a2a",
        "on-primary-fixed-variant": "#004494",
        "surface-container-lowest": "#0e0e0e",
        "surface-variant": "#353534",
        "primary": "#adc6ff",
        "on-secondary-container": "#a3b8e8",
        "on-secondary-fixed": "#001a41",
        "tertiary-fixed": "#ffdcc4",
        "surface": "#131313",
        "tertiary-fixed-dim": "#ffb780",
        "on-tertiary": "#4e2600",
        "on-primary-fixed": "#001a41",
        "surface-bright": "#393939",
        "on-primary-container": "#00285c",
        "on-secondary-fixed-variant": "#31466f",
        "on-tertiary-fixed-variant": "#6f3800",
        "on-error": "#690005",
        "surface-container": "#201f1f",
        "inverse-surface": "#e5e2e1",
        "surface-tint": "#adc6ff",
        "tertiary": "#ffb780",
        "surface-container-low": "#1c1b1b",
        "on-tertiary-container": "#442000",
        "surface-container-highest": "#353534",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#b1c6f7",
        "on-background": "#e5e2e1",
        "on-secondary": "#193057",
        "on-tertiary-fixed": "#2f1400",
        "on-surface-variant": "#c2c6d5",
        "on-surface": "#e5e2e1",
        "inverse-primary": "#005ac1",
        "secondary-fixed": "#d8e2ff",
        "outline-variant": "#424753",
        "inverse-on-surface": "#313030",
        "primary-fixed": "#d8e2ff",
        "background": "#131313",
        "primary-fixed-dim": "#adc6ff",
        "error-container": "#93000a",
        "secondary-container": "#344972",
        "outline": "#8c909f",
        "surface-dim": "#131313"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
